### ISSUE TITLE
No connection adapters were found

### ISSUE THREAD

**Issue by boydthomson** [tubearchivist/jellyfin#33]
I can't get this working with jellyfin 10.8.13 running at 192.168.1.100

This is what I get from the docker exec command:

tubearchivist-jf:~# docker exec -it tubearchivist-jf python main.py
Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    main()
  File "/app/main.py", line 10, in main
    Jellyfin().ping()
  File "/app/src/connect.py", line 55, in ping
    response = self.get("Users")
               ^^^^^^^^^^^^^^^^^
  File "/app/src/connect.py", line 26, in get
    response = requests.get(url, headers=self.headers, timeout=TIMEOUT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '"http://192.168.1.100"/Users'

**Comment by boydthomson** [comment]
My bad, found the typo.  Sorry.
